### ISSUE TITLE
Integration with PocketSphinx

### ISSUE THREAD

**Issue by himuura** [shenfei/deluminator#2]
Hi there! First of all, congrats!! It's a great project. I saw the project today on Cornell site, read it from top to bottom and it's a great analysis on Jasper, totally on the point.
Now, my question: is it possible to use this training.py script to train pocketsphinx? If not, how does this python script work? How did you guys define the STT_ENGINE it on the profile.yml on Jasper?

I would be most thankful if you could provide a video link with the training session (the Cornell videos are not available anymore).
Thanks in advance!
Hats of for you guys!

**Comment by shenfei** [comment]
Hi @himuura, I think you confused this project with another one.
So I'll close this issue.
